name: Rust

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cd staged-sg-filter; cargo fmt --check --verbose
    - name: Lint
      run: cd staged-sg-filter; cargo clippy
    - name: Build
      run: cd staged-sg-filter; cargo build --verbose
    - name: Run tests
      run: cd staged-sg-filter; cargo test --verbose; cargo test --verbose --no-default-features
    - name: Test no-std
      run: |
        cd test_no_std
        rustup target add thumbv7em-none-eabihf
        cargo build --verbose
